# coding: utf-8

"""
    aind-session-json-service

     ## aind-session-json-service  Run metadata mapper to create a session metadata  

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_session_json_service_async_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.IsolatedAsyncioTestCase):
    """HealthcheckApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = HealthcheckApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_health(self) -> None:
        """Test case for get_health

        Perform a Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
